02-set-up.Rmd, 04-workflow.Rmd
Comments welcome - will say when ready to merge.
=> Review of Chapter 4

03-programming.Rmd, 09-collaboration.Rmd
=> Fixed typo

05-data-capentry.Rmd
You may also want to fix the filename itself via `git mv ...`.
=> Typo correction

06-visualisation.Rmd
=> Reword discussion of OSs in relation to graphics

08-hardware.Rmd
Details: https://github.com/HenrikBengtsson/Wishlist-for-R/issues/6
=> SI standard: kB (not KB)

02-set-up.Rmd
Changes following review by @garrettgman (thanks for that, any feedback welcome).
=> C2 rev garret

01-introduction.Rmd, 07-performance.Rmd, DESCRIPTION
Probably needs some more work in final section but is now cohesive and all sections have content.
=> First draft of Chapter 1 done

02-set-up.Rmd, 05-data-carpentry.Rmd
Holding place for incorporating feedback from Garrett on Chapter 2. Not sure why everything's committed twice - something to do with `git rebase` I guess.
=> C2 rev garrett

01-introduction.Rmd
=> Make some cosmetic changes

04-workflow.Rmd, 05-data-carpentry.Rmd, data/verbs.csv
=> Updates to Chapter 5

05-input-output.Rmd, 07-performance.Rmd, 09-collaboration.Rmd, 10-learning.Rmd, refs.bib
=> Rewrite binary benchmark section, review chatpers 7, 9 and 10

02-set-up.Rmd
Just a simple fix: replace "XX" into the actual chapter number. More of an exercise for in creating a pull request.
=> Fixed a reference to the chapter collaboration

09-collaboration.Rmd, NAMESPACE
@Robinlovelace Are you happy for me to add this?
=> Add Lewis Carroll quote object names

09-collaboration.Rmd
=> Referee's comments

10-learning.Rmd
Holding pen for updates and discussion of Chapter 10 after the review - may take a day or 2 to finish this PR, will let you know when I think this is good to merge.
=> Review c10

05-input-output.Rmd
Adding in Pre-req
Adding in para on httr
Typos
=> Chapter 5 review

09-collaboration.Rmd
Only removing an out of date comment
=> Trivial pull request

appendix.Rmd, index.Rmd
Moving "building the book" to an Appendix since it's confusing for new programmers.
=> Building instructions -> appendix

02-set-up.Rmd
Fix #163 - thanks Bill, greatly appreciated.
Forgot only in data frames are columns lists.
Think this is a better use case now.
Surprisingly fast (~5 and 3 s on my laptop).
Update note that it may take time to include RAM.
=> Calculate median per col not per element.

02-set-up.Rmd
I didn't go through the entire chapter to avoid merge conflicts with your PR
=> Chapter 2: Adding () to function calls

03-programming.Rmd, refs.bib
Reference source (R manual), add rmdwarning
=> Minor edits to byte compile installation section +

01-introduction.Rmd
Some typo corrections and grammatical fixes/improvements
=> Chapter 1 corrections

02-set-up.Rmd, 05-input-output.Rmd
see closed issue https://github.com/csgillespie/efficientR/issues/214
=> use text references for captions

07-performance.Rmd
Hi, thank you for writing this awesome book =)
It's relevant for the novice as well as the advanced user and very pleasant to read.
I noticed & corrected some typos in part 7.
Thanks again ;)
=> Part7 correct some typos

04-workflow.Rmd
The first reference to PMBoK2000 in "4.3.1 'Chunking' your work" should be in parentheses.
=> Changed a reference to parenthesized

06-data-carpentry.Rmd
Addresses the first point in https://github.com/csgillespie/efficientR/issues/239.
=> Hide solutions in Section 6.3

02-set-up.Rmd
has moved from revolution r to https://mran.microsoft.com/open
=> fixed broken link to MRO

01-introduction.Rmd
Minor fixes to grammar, punctuation, syntax across `01-introduction.Rmd`.
=> 01-introduction.Rmd - minor fixes

01-introduction.Rmd, 02-set-up.Rmd
Larger changes are as follows:
- capitalized "Figure" consistently in 01-introduction and 02-setup
- removed one blockquote making it difficult to distinguish code from text
- added detail to TIBCO
- minor spelling, grammar, punctuation issues
=> 02-setup - fixes to grammar, language, consistency

02-set-up.Rmd
Fixes issue 285 (https://github.com/csgillespie/efficientR/issues/285)
=> moved bracket

06-data-carpentry.Rmd
changed the order of "sex" and "age" in the section 6.3.2.
=> 6.3.2 Changing the order of "age" and "sex"
